language: cpp

compiler:
  - clang

cache: apt

before_script:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -y libgflags-dev libgoogle-glog-dev
  - mkdir -p out/Debug
  - cd out/Debug
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ../../src

script:
 - make -j4 
 - CTEST_OUTPUT_ON_FAILURE=1 make test 
